#  bundle exec jekyll serve --config .\_config.yml,.\_config.dev.yml

safe: true
title: Recipes
baseurl: '/recipes' # the subpath of your site, e.g. /blog
url: 'https://nicholas.fish' # the base hostname & protocol for your site, e.g. http://example.com

api_baseurl: https://nicholasfishrecipes.azurewebsites.net
auth_callback: 'https://nicholas.fish/recipes/'

include: ['.well-known/microsoft-identity-association.json']

# Build settings
theme: minima
permalink: pretty
plugins:
  - jekyll-feed
